# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  database: stock_search_development

test: 
  <<: *default
  database: stock_search_test

production:
  <<: *default
  database: stock_search_production
  username: stock_search
  password: <%= ENV['STOCK_SEARCH_DATABASE_PASSWORD'] %>